# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: The Roys Blog

# Short description (goes below the title; it will also be used in the RSS feed)
description: A day in the life of a Roy

author: Christofer Roy
author_email: christofer.roy@gmail.com

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

tag_page_layout: tag_page
tag_page_dir: tag

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 
baseurl: 

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://theroys.space/

#### Under the Hood Stuff #####

markdown: rdiscount

permalink: pretty

paginate: 5

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: ['.gitignore', 'Gemfile', 'Gemfile.lock', 'Rakefile']
